name: Deploy U2U Wallet
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: edwardultra/u2u-wallet:latest

      - name: Deploy
        run: |
          command -v ssh-agent >/dev/null || ( apk add --update openssh )
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan volta.northstudio.dev >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh -t -t ubuntu@$SSH_KNOWN_HOSTS "cd ~ && docker compose pull && docker compose up -d"
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
          SSH_KNOWN_HOSTS: ${{ secrets.PRODUCTION_HOST }}
